title: Michael Walczyk
logo: /assets/img/logo.png
description: Media Artist & Graphics Programmer
description: >
  Media Artist & Graphics Programmer
  <br>
  <br>
  <a href="https://www.instagram.com/mwalczyk/">ğŸ“· Instagram</a> 
  <br>
  <a href="https://github.com/mwalczyk">ğŸ’» Github</a>
  <br>
  <a href="https://www.linkedin.com/in/mike-walczyk-37267358">ğŸ“ LinkedIn</a>
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
